title: AWS
email: sfawcett123@icloud.com
description: AWS Design Repo 
url: "https://sfawcett123.github.io/aws" 
github_username:  sfawcett123
theme: just-the-docs

# Build settings
plugins:
  - jekyll-feed

aux_links: 
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
